{
	"name"			:"Addon Management",
	"version"		:"1.0",
	"depends"		:["base","account"],
	"author"		:"richard",
	"category"		:"Management",
	"website"		:"htpp://vitraining.com",
	"Description"	:"...",
	"data"			:[
		"security/security.xml",
		"security/ir.model.access.csv",
		"asset/main.xml",
		"asset/datauser.xml",
	 	"asset/lokasi.xml",
	 	"asset/ruang.xml",
	 	"asset/subruang.xml",
	 	"asset/unit.xml",
	 	"asset/subunit.xml",
	 	"asset/merk.xml",
	 	"asset/kodeperangkat.xml",
	 	"asset/kelompokperangkat.xml",
	 	"asset/perangkatdc.xml",
	 	"asset/perangkatnondc.xml",
	 	"asset/powerdistribution.xml",
	 	"asset/landistribution.xml",
	 	"asset/capacity.xml",
	 	"asset/utilisasiperangkatdc.xml",
	 	"asset/docrecruitment.xml",
	 	"asset/docsop.xml",
	 	"asset/docbcp.xml",
	 	"asset/docberita.xml",
	 	"asset/docagenda",
	],
	"installable": True,
	"auto_install": False,
	"application": True,
}